#!/bin/bash
# Cleanup script to remove unused backend and deprecated files
# Run this from the FlowcharDesigner project root directory

echo "========================================"
echo " FlowcharDesigner Project Cleanup"
echo "========================================"
echo ""
echo "This script will delete:"
echo "- Backend directory (Python server)"
echo "- Backend-related scripts"
echo "- Unused widget files"
echo "- Deprecated utilities"
echo "- Outdated documentation"
echo ""
read -p "Press Enter to continue..."

echo ""
echo "[1/6] Removing backend directory..."
[ -d backend ] && rm -rf backend && echo "✓ backend/ deleted" || echo "✗ backend/ not found"

echo ""
echo "[2/6] Removing backend scripts..."
[ -f start_backend.bat ] && rm -f start_backend.bat && echo "✓ start_backend.bat deleted" || echo "✗ start_backend.bat not found"
[ -f start_backend.sh ] && rm -f start_backend.sh && echo "✓ start_backend.sh deleted" || echo "✗ start_backend.sh not found"
[ -f test_backend.py ] && rm -f test_backend.py && echo "✓ test_backend.py deleted" || echo "✗ test_backend.py not found"
[ -f find_ip.bat ] && rm -f find_ip.bat && echo "✓ find_ip.bat deleted" || echo "✗ find_ip.bat not found"
[ -f find_ip.sh ] && rm -f find_ip.sh && echo "✓ find_ip.sh deleted" || echo "✗ find_ip.sh not found"

echo ""
echo "[3/6] Removing unused widget files..."
[ -f lib/widgets/flowchart_viewer.dart ] && rm -f lib/widgets/flowchart_viewer.dart && echo "✓ flowchart_viewer.dart deleted" || echo "✗ flowchart_viewer.dart not found"
[ -f lib/widgets/enhanced_flowchart_viewer.dart ] && rm -f lib/widgets/enhanced_flowchart_viewer.dart && echo "✓ enhanced_flowchart_viewer.dart deleted" || echo "✗ enhanced_flowchart_viewer.dart not found"
[ -f lib/widgets/vertical_flowchart_viewer.dart ] && rm -f lib/widgets/vertical_flowchart_viewer.dart && echo "✓ vertical_flowchart_viewer.dart deleted" || echo "✗ vertical_flowchart_viewer.dart not found"
[ -f lib/widgets/html_flowchart_viewer.dart ] && rm -f lib/widgets/html_flowchart_viewer.dart && echo "✓ html_flowchart_viewer.dart deleted" || echo "✗ html_flowchart_viewer.dart not found"

echo ""
echo "[4/6] Removing unused utilities..."
[ -f lib/utils/mermaid_parser.dart ] && rm -f lib/utils/mermaid_parser.dart && echo "✓ mermaid_parser.dart deleted" || echo "✗ mermaid_parser.dart not found"
[ -f lib/config/app_config.dart ] && rm -f lib/config/app_config.dart && echo "✓ app_config.dart deleted" || echo "✗ app_config.dart not found"

echo ""
echo "[5/6] Removing outdated documentation..."
[ -f QUICKSTART.md ] && rm -f QUICKSTART.md && echo "✓ QUICKSTART.md deleted" || echo "✗ QUICKSTART.md not found"
[ -f START_HERE.md ] && rm -f START_HERE.md && echo "✓ START_HERE.md deleted" || echo "✗ START_HERE.md not found"
[ -f TEST_CONNECTION.md ] && rm -f TEST_CONNECTION.md && echo "✓ TEST_CONNECTION.md deleted" || echo "✗ TEST_CONNECTION.md not found"
[ -f ARCHITECTURE.md ] && rm -f ARCHITECTURE.md && echo "✓ ARCHITECTURE.md deleted" || echo "✗ ARCHITECTURE.md not found"
[ -f MIGRATION_NOTES.md ] && rm -f MIGRATION_NOTES.md && echo "✓ MIGRATION_NOTES.md deleted" || echo "✗ MIGRATION_NOTES.md not found"

echo ""
echo "[6/6] Cleanup complete!"
echo ""
echo "Next steps:"
echo "1. Run 'flutter analyze' to verify no broken imports"
echo "2. Run 'flutter build apk --debug' to test compilation"
echo "3. Test app functionality"
echo ""
read -p "Press Enter to exit..."
